name: sdf-hoi-custom3
trial_name: custom3-coarse
tag: ""
seed: 42

use_barf: true
dataset:
  name: hoi
  root_dir: /remote-home/jiangshijian/new_exp/data
  seq_name: custom3
  img_wh:
    - 640
    - 480
  # img_downscale: 1 # specify training image size by either img_wh or img_downscale
  start_idx : 0
  end_idx: 100
  step: 1
  n_test_traj_steps: 60
  select_win: 5
  load_data_on_gpu: true
  normalize_mesh: false
  obj_path: /remote-home/jiangshijian/new_exp/HHOR/homan_obj/mesh_samples/shoes_simple/1229a2e6e97e_A_basketball_shoes_.obj
  meta_dir: /remote-home/jiangshijian/new_exp/Proghor/FeatureMatcher/pose_optimizer/custom3_indiviual/pred
  sample_foreground_ratio: 0.8



model:
  name: neus_wotex
  radius: 1.5
  num_samples_per_ray: 1024
  train_num_rays: 256
  max_train_num_rays: 8192
  grid_prune: true
  grid_prune_occ_thre: 0.001
  dynamic_ray_sampling: true
  dynamic_sampleing_ratio: true
  batch_image_sampling: true
  randomized: true
  ray_chunk: 4096
  cos_anneal_end: ${trainer.max_steps}
  learned_background: false
  background_color: random
  variance:
    init_val: 0.3
    modulate: false
  geometry:
    name: volume-sdf
    radius: ${model.radius}
    feature_dim: 65
    grad_type: analytic
    isosurface:
      method: mc
      resolution: 512
      chunk: 2097152
      threshold: 0.
    xyz_encoding_config:
      otype: ProgressiveBandHashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 32
      per_level_scale: 1.3195079107728942
      include_xyz: true
      start_level: 4
      start_step: 5000
      update_steps: 1000
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 2
      sphere_init: true
      sphere_init_radius: 0.5
      weight_norm: true

system:
  name: sdf-barf-system
  loss:
    lambda_rgb_mse: 0.
    lambda_rgb_l1: 1.
    lambda_mask: 1.
    lambda_eikonal: 0.1
    lambda_normal: 0.1
    lambda_curvature: 0.
    lambda_sparsity: 0.1
    lambda_distortion: 0.
    lambda_opaque: 0.
    lambda_correspondence: 1.
    lambda_relight: 0.
    sparsity_scale: 1.
    correspondence_start_iters: 500
  optimizer:
    name: AdamW
    args:
      lr: 0.01
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry:
        lr: 0.01
      variance:
        lr: 0.001
  pose_optimizer:
    name: Adam
    args:
      lr: 0.001
  warmup_steps: 500
  scheduler:
    name: SequentialLR
    interval: step
    milestones:
      - ${system.warmup_steps}
    schedulers:
      - name: LinearLR # linear warm-up in the first system.warmup_steps steps
        args:
          start_factor: 0.01
          end_factor: 1.0
          total_iters: ${system.warmup_steps}
      - name: ExponentialLR
        args:
          gamma: ${calc_exp_lr_decay_rate:0.1,${sub:${trainer.max_steps},${system.warmup_steps}}}

checkpoint:
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}

export:
  chunk_size: 2097152
  export_vertex_color: true

trainer:
  max_steps: 5000
  log_every_n_steps: 100
  num_sanity_val_steps: 0
  val_check_interval: 5000
  limit_train_batches: 1.0
  limit_val_batches: 2
  enable_progress_bar: true
  precision: 16
